### ISSUE TITLE
For tf.keras.applications.resnet_v2.ResNet152V2 model, np.linalg.eig(X) return complex eigenvalue, breaks vectors=True option

### ISSUE THREAD

**Issue by PANUOA** [CalculatedContent/WeightWatcher#117] opened 2022-04-21 02:13 UTC
For tf.keras.applications.resnet_v2.ResNet152V2 model, np.linalg.eig(X) return complex eigenvalue. Which make np.histogram function not working (not accept complex number as input).

Code:
The weightwatcher.py Line 2765
evals, V = np.linalg.eig(X)

And these are some of layer ID meet this problem: 136, 140, 148, etc.

**Comment by charlesmartin14** [comment] 2022-04-21 05:55
Actually, I don't think the code should reach line 2765 unless the option
`vectors=True`
is set

Im a little surprised it does this.  Debugging

**Comment by PANUOA** [comment] 2022-04-21 06:34
yes. It worked. Thank you.

**Comment by charlesmartin14** [comment] 2022-04-21 06:46
The issue needs to remain open or reclassified as a the problem is specifically with the method
`analyze_eigenvectors()
`

**Comment by charlesmartin14** [comment] 2022-10-06 04:03
This has been fixed in the Trunk and will be released in ww0.6.x

The fix is to replace the `numpy.linalg.eig()` solver with the scipy version

**Closed by charlesmartin14** 2022-10-06 04:03 UTC
